<a href="https://colab.research.google.com/github/abidur0177/TIme-Series-Prediction/blob/main/Feature_extraction_and_labeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import tensorflow as tf
import numpy as np

In [35]:
dataset = tf.data.Dataset.range(10)

for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


### Windowing the data

In [18]:
# Generate a tf dataset
dataset = tf.data.Dataset.range(10)

# Window the dataset of size 5 and shift 1
dataset = dataset.window(size=5, shift=1)

for window_dataset in dataset:
  print(window_dataset) # Each window dataset is itself is a tf dataset

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>


In [19]:
# See the values of each window
for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


In [33]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# To remove the last unmatched window_dataset we can use the set the drop_remainder parameter to True
dataset = dataset.window(size=5, shift=1, drop_remainder=True)

# See the values of each window
for window_dataset in dataset:
  print([item.numpy() for item in window_dataset])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


### Flattening the window

In [43]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch of tensors
dataset = dataset.flat_map(lambda window: window.batch(5))

# Print the results
for window in dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


### Group each tensor of the dataset and create the labels

In [44]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch of tensors
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create a tuple while the first four elements are consideres as the features and the last element is as the label
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

for window in dataset:
  print(f"This are the features: {window[0].numpy()}")
  print(f"This is the label: {window[1]} \n")

This are the features: [0 1 2 3]
This is the label: 4 

This are the features: [1 2 3 4]
This is the label: 5 

This are the features: [2 3 4 5]
This is the label: 6 

This are the features: [3 4 5 6]
This is the label: 7 

This are the features: [4 5 6 7]
This is the label: 8 

This are the features: [5 6 7 8]
This is the label: 9 



In [45]:
# We can get this another way
for x,y in dataset:
  print(f"x = {x.numpy()}")
  print(f"y = {y.numpy()}\n")

x = [0 1 2 3]
y = 4

x = [1 2 3 4]
y = 5

x = [2 3 4 5]
y = 6

x = [3 4 5 6]
y = 7

x = [4 5 6 7]
y = 8

x = [5 6 7 8]
y = 9



### Shuffle the dataset

In [48]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch of tensors
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create a tuple while the first four elements are consideres as the features and the last element is as the label
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

# Shuffle the order of the windows in the dataset
dataset = dataset.shuffle(buffer_size=10)

for window in dataset:
  print(f"This are the features: {window[0].numpy()}")
  print(f"This is the label: {window[1]} \n")

This are the features: [1 2 3 4]
This is the label: 5 

This are the features: [3 4 5 6]
This is the label: 7 

This are the features: [0 1 2 3]
This is the label: 4 

This are the features: [2 3 4 5]
This is the label: 6 

This are the features: [5 6 7 8]
This is the label: 9 

This are the features: [4 5 6 7]
This is the label: 8 



### Creating batches for training the dataset

In [50]:
# Generate a tf dataset with 10 elements (i.e. numbers 0 to 9)
dataset = tf.data.Dataset.range(10)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch of tensors
dataset = dataset.flat_map(lambda window: window.batch(5))

# Create a tuple while the first four elements are consideres as the features and the last element is as the label
dataset = dataset.map(lambda window: (window[:-1], window[-1]))

# Shuffle the order of the windows in the dataset
dataset = dataset.shuffle(buffer_size=10)

# Create batches of windows for the training purpose. The prefetch function put the next batch into the buffer to optimize the training time
dataset = dataset.batch(2).prefetch(buffer_size=1) # This code takes two windows and create a batch out of this

for window in dataset:
  print(f"This are the features: {window[0].numpy()}")
  print(f"This is the label: {window[1]} \n")

This are the features: [[5 6 7 8]
 [1 2 3 4]]
This is the label: [9 5] 

This are the features: [[2 3 4 5]
 [4 5 6 7]]
This is the label: [6 8] 

This are the features: [[0 1 2 3]
 [3 4 5 6]]
This is the label: [4 7] 

